package:
  format-version: "1.0.0"
  name: "mc_apps_pic32cm_mc"
  version: "v3.3.1"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.17.0"
    - name: "x2c"
      type: "package"
      version: "v1.4.0"