package:
  format-version: "1.0.0"
  name: "mc_apps_pic32cm_mc"
  version: "v3.4.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
     - name: "motor_control"
       type: "package"
       version: "fixed_point_dev_imprv"