configName: mclv2_pic32_cm_mc_pim
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32CM1216MC00048
projectName: ''
settings:
  PackageFilter: BU;csp;mc_apps_pic32cm_mc;mc_apps_pic32cm_mc - Copy;mc_apps_pic32mk;mc_apps_sam_c2x;mc_apps_sam_d5x_e5x;mc_apps_sam_d5x_e5x__;mc_apps_sam_e7x_s7x_v7x;motor_control;motor_control
    - Copy;x2c
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-MC_DFP\1.2.52\PIC32CM1216MC00048\atdf\PIC32CM1216MC00048.atdf
