format_version: v1.0
type: UniqueComponent
attributes: {id: pdec}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: ENCODER_POS_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: PDEC_QDECPositionGet}
  - type: String
    attributes: {id: ENCODER_POS_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: ''}
  - type: String
    attributes: {id: ENCODER_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: PDEC_QDECStart}
  - type: String
    attributes: {id: ENCODER_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: PDEC_QDECStop}
  - type: File
    attributes: {id: PDEC_COUNTER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: PDEC_COUNTER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: PDEC_CTRLA_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: PDEC_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '48000000'}
  - type: File
    attributes: {id: PDEC_HALL_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: PDEC_HALL_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: PDEC_HALL_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Hex
    attributes: {id: PDEC_INTENSET}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '8'}
  - type: Boolean
    attributes: {id: PDEC_INTENSET_VLC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: File
    attributes: {id: PDEC_QDEC_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Menu
    attributes: {id: PDEC_QDEC_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: PDEC_QDEC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '403', y: '237', id: pdec}
